### ISSUE TITLE
startWrite() function not working properly

### ISSUE THREAD

**Issue by TMRh20** [TMRh20/nrf_to_nrf#5]
This function will probably never work properly until/unless we get interrupts working for these devices. Opening an issue for tracking purposes.

**Comment by 2bndy5** [comment]
Maybe `txStandBy()` could be put to better use here. Although, that idea might imply different behavior from `RF24::txStandBy()`.

**Comment by TMRh20** [comment]
How? You assume I know what I'm doing or something. :p
Without interrupts we can't really do anything in the background, so I don't think we can get the functionality working akin to RF24.

**Comment by 2bndy5** [comment]
yeah it wouldn't work like in RF24.

```c
startWrite();
txStandBy();
```
Indeed, we'd need interrupt support to implement like RF24 does, but I was thinking in a less-blocking way than `write()`.

**Comment by TMRh20** [comment]
Hmm, that might be worth looking into. 

I really should get at least one more of these devices, they are pretty nice and I could troubleshoot more effectively.

**Comment by 2bndy5** [comment]
I picked up the XIAO expansion board and a ST-Link V2 so I could do even more.

I'd recommend a Microbit because it has a builtin debugging chip, but it has little Arduino support. Microbits are better for using MicroPython or Zephyr Project.
